### PR TITLE
Updating bits

### PR DESCRIPTION
**Pull request by jimangel**
👋 feel free to close this if you're not interested in merging.

Figured I'd contribute my changes back upstream :)

Hope things are well!

/priority none
/sig none
/lgtm
/approve
/check-cla

### CODE REVIEW

**Comment by jimangel** [comment]
@zparnold it would be an honor to be the 3rd commit in this repo 😝

**Comment by zparnold** [comment]
Hey man! I’d love to have the contribution! Thanks for thinking of me and the upstream!

**Comment by zparnold** [comment]
Things are super well, hope they are with you also!

**Comment by zparnold** [comment]
Looks like I can’t reopen, but if you do I’d be happy to merge!

**Comment by jimangel** [comment]
That's what I get for cleaning up my forks 😢  - no worries! Things are good, we'll have to catch up soon! If I find it laying around, I'll re-open. Cheers!

**Pull request closed without merging**
